### PR TITLE
fix: java 14 seems OK

### PR DESCRIPTION
**Pull request by crowmagnumb**
I've set it to null for now (and do null checks where necessary) until we find some Java version that doesn't work and then we can set it to that if need be.

### CODE REVIEW

**Comment by crowmagnumb** [comment]
Any comment on this?

**Comment by NathanWalker** [comment]
@crowmagnumb not sure null is best but perhaps a higher version range.
@NathanaelA curious your take here.

**Comment by crowmagnumb** [comment]
Randomly picking a higher version just seems like a way to push the problem down the line until it happens again when it is possible we never have this problem again. If so, we never have to touch it. If we find a version that doesn't work then we change it to that version until it works with that version and we set it to null again. If we set it to some random version in the future, than when that version comes out we will not support it, not by nature of support, but because we randomly picked that version and then we have to go in and pick another higher number, and repeat.  :)

**Comment by NathanaelA** [comment]
I don't disagree with @crowmagnumb - locking version numbers is an annoying problem when updates don't actually break things, it just becomes more of an annoyance, especially like in this case where the next version of Java does work as-is.

However, I can understand why the code has version ranges, because it makes it easy to know what failed when a new version comes out and allow the user to downgrade in the meantime.  W/o a version check they have no idea why it is failing..

I could go either way, however, I don't believe Java has really introduced any major breaking things that affected us very often, so I think I might lean a bit more towards Ken's idea of just removing the check...

**Review by NathanWalker — APPROVED** [review]

**Pull request merged**
